### Command操作
POST http://127.0.0.1:8090/treeNode/command
Accept: application/json
Content-Type: application/json

{
  "command": "treeNode --option=query --type=children --id=5 --level=2"
}


### reset
POST http://127.0.0.1:8090/treeNode/reset
Accept: text/plain

### 递归初始化数据
POST http://127.0.0.1:8090/treeNode/init
Accept: application/json
Content-Type: application/json

{
  "basePid": -1,
  "path": "D:/gradle-7.4.2"
}


### 递归查询初始化数据
POST http://127.0.0.1:8090/treeNode/logPrintQuery
Accept: application/json
Content-Type: application/json

{
  "id": 1
}
