### hello
GET http://127.0.0.1:8080/hello


### login
POST http://127.0.0.1:8080/doLogin
Content-Type: application/x-www-form-urlencoded

name=admin&passwd=123

### logout
GET http://127.0.0.1:8080/logout