### hello
GET http://127.0.0.1:8090/hello/zhuzhenjie
Accept: text/plain



### write to file
POST http://127.0.0.1:8090/file/write
Content-Type: application/json
Accept: text/plain

{
  "filename": "integration.txt",
  "text": "spring boot integration"
}


### 测试 tcp client
GET http://127.0.0.1:8090/tcp-client
